const endpoint=(model,key)=>`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;
export async function callGemini(prompt,{timeout=8000}={}){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('Gemini indisponível');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(endpoint(process.env.GEMINI_MODEL||'gemini-2.5-flash',key),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.9}}),signal:controller.signal});if(!res.ok)throw new Error(`Gemini HTTP ${res.status}`);const json=await res.json();return JSON.parse(json.candidates?.[0]?.content?.parts?.[0]?.text||'{}');}finally{clearTimeout(timer);}}
const pick=list=>list[Math.floor(Math.random()*list.length)];
const portraitLooks=['cabelo preto curto e barba cheia bem cuidada','cabelo castanho ondulado e barba rala','cabelo loiro médio e barba aparada','cabelo cacheado volumoso e rosto sem barba','cabeça raspada e barba desenhada','cabelo ruivo acobreado e barba curta','cabelo grisalho charmoso e barba grisalha curta','cabelo castanho liso penteado para trás e cavanhaque'];
const portraitOutfits=['camisa social azul-marinho aberta sobre camiseta branca','suéter de tricô cor mostarda','jaqueta jeans sobre camiseta clara','blazer casual cinza com camiseta preta','camisa de linho clara','camisa polo verde-escura'];
const portraitScenes=['uma rua urbana com prédios desfocados','uma orla de praia no fim de tarde','um café aconchegante com luzes quentes','um parque arborizado','uma cidade histórica com um ônibus vermelho desfocado ao fundo','uma marina com barcos desfocados ao fundo'];
async function generateImage(prompt,timeout){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('Gemini indisponível');const model=process.env.GEMINI_IMAGE_MODEL||'gemini-2.5-flash-image',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(endpoint(model,key),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['IMAGE','TEXT']}}),signal:controller.signal});if(!res.ok)throw new Error(`Gemini Image HTTP ${res.status}`);const json=await res.json(),part=json.candidates?.[0]?.content?.parts?.find(p=>p.inlineData?.data);if(!part)throw new Error('Imagem ausente');return `data:${part.inlineData.mimeType||'image/png'};base64,${part.inlineData.data}`;}finally{clearTimeout(timer);}}
export async function generateOraclePortrait(profile,{timeout=25_000}={}){const prompt=`Fotografia de retrato realista, enquadramento quadrado do busto com o rosto centralizado, de um homem adulto fictício e inexistente, com aparência claramente entre 28 e 45 anos, sorrindo simpático para a câmera, com ${pick(portraitLooks)}, vestindo ${pick(portraitOutfits)}, em ${pick(portraitScenes)}, luz natural suave e fundo desfocado. Variação ${profile.seed%997}. A pessoa é 100% gerada por IA. Não retrate pessoa real, celebridade, texto, marca, logotipo, nudez, erotização, uniforme, estereótipo cultural ou aparência de menor de idade.`;return generateImage(prompt,timeout);}
const pvScene=s=>s.princesoPercent===100?'um homem adulto boiando relaxado numa boia inflável de flamingo, com drink na mão e óculos escuros, ao lado de uma canoa vazia com dois remos, no meio de um mar de tempestade':s.vikingPercent>=75?'um homem adulto com capacete de viking de festa remando com garra e sorriso confiante uma canoa de madeira em mar de ondas altas, com respingos épicos':s.vikingPercent>=50?'um homem adulto remando uma canoa com um remo só e expressão de esforço pela metade, enquanto o segundo remo descansa embrulhado como presente ao lado dele':'um homem adulto sentado como passageiro na canoa, mexendo no celular com o remo intocado no colo, com o posto do remador vazio em pleno mar agitado';
export async function generatePvScene(scores,{timeout=25_000}={}){const prompt=`Fotografia realista com humor de sátira: ${pvScene(scores)}. Luz dramática de tempestade, estilo cinematográfico, cores intensas, composição horizontal com a cena centralizada. O homem tem entre 30 e 45 anos, é fictício e inexistente, com expressão cômica. Variação ${Math.floor(Math.random()*997)}. Sem texto, sem marca, sem logotipo, sem emoji, sem pessoa real ou celebridade, sem nudez, sem menor de idade.`;return generateImage(prompt,timeout);}
