import { AXES } from './question-bank.js';
export function scoreRound(questions,answers){
 const axes=Object.fromEntries(AXES.map(a=>[a,{viking:0,princeso:0,total:0}]));let viking=0,princeso=0,total=0;const examples=[];
 for(const q of questions){const choice=q.choices.find(c=>c.id===answers[q.id]);if(!choice)throw new Error('Resposta inválida ou ausente');const weight=choice.intensity;total+=weight;choice.category==='VIKING'?viking+=weight:princeso+=weight;const bucket=axes[q.axis];bucket.total+=weight;bucket[choice.category.toLowerCase()]+=weight;examples.push({axis:q.axis,text:choice.text.slice(0,120)});}
 const pct=n=>Math.round((n/Math.max(total,1))*100);const axisScores=Object.fromEntries(Object.entries(axes).map(([k,x])=>[k,{viking:x.total?pctAxis(x.viking,x.total):50,princeso:x.total?pctAxis(x.princeso,x.total):50}]));
 const strongest=Object.entries(axisScores).sort((a,b)=>b[1].viking-a[1].viking)[0][0];const warning=Object.entries(axisScores).sort((a,b)=>b[1].princeso-a[1].princeso)[0][0];
 return {vikingPercent:pct(viking),princesoPercent:100-pct(viking),axes:axisScores,strongestViking:strongest,dominantPrinceso:warning,examples:examples.slice(0,3)};
}
const pctAxis=(n,t)=>Math.round(n/t*100);
export function templateDiagnosis(s){if(s.princesoPercent===100)return {title:'Princeso Absoluto — Perigo na Embarcação',diagnosis:'O remo virou item decorativo e toda a expedição foi terceirizada para você. Resultado recreativo, mas o meme não teve dúvida.',greatestTalent:'transformar iniciativa alheia em serviço completo',warningSign:'responsabilidade afetiva em modo avião',verdict:'FOGE BINO QUE É ROUBADA !!',shareLine:'100% Princeso: nem passageiro, já pediu serviço de bordo.',seal:'FOGE BINO QUE É ROUBADA !!'};const high=s.vikingPercent>=75,mid=s.vikingPercent>=50,variant=(s.strongestViking.length+s.dominantPrinceso.length)%3;const titles=high?['Viking Autêntico — Item Raro Encontrado','Capitão da Reciprocidade','Viking com Remo Próprio']:mid?['Viking do Remo Curto','Capitão da Responsabilidade Seletiva','Viking de Fim de Semana']:['Lorde do “Você que Sabe”','Passageiro Clandestino','Príncipe Ragnar da Enrolação'];return {title:titles[variant],diagnosis:high?'O barco tem dois remos e, milagre estatístico, ele usa o dele. Há presença, conversa e responsabilidade — sem transformar você em central de operações.':mid?'Ele até entra no barco, mas em algumas tempestades descobre uma vocação para passageiro. Existe parceria; falta consistência quando o mar engrossa.':'Você não está numa relação: está administrando uma expedição com um passageiro que pergunta se falta muito. O charme aparece; a responsabilidade, mediante agendamento.',greatestTalent:s.strongestViking,warningSign:s.dominantPrinceso,verdict:high?'Enfrenta a tempestade em parceria.':mid?'Rema, mas ainda solta o remo quando complica.':'Transforma planejamento conjunto em trabalho terceirizado.',shareLine:high?'O barco tem dois remos — e ele usa o dele.':mid?'Viking no trailer; passageiro em alguns episódios.':'Ele não enfrenta a tempestade: pergunta se você trouxe o guarda-chuva.',seal:null};}
